CREATE TABLE student(
    id INT GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(40) NOT NULL,
    lastname VARCHAR(40) NOT NULL
);

CREATE TABLE logitem(
    id INT GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
    date       DATE NOT NULL,
    message    VARCHAR(300) NOT NULL,
    student_id INT CONSTRAINT fktaco111gkh811es5yjkgaaj2n REFERENCES student
);

CREATE TABLE student_logitem(
    student_id INT NOT NULL CONSTRAINT fkp72iahqtk507m11eb29nat70w REFERENCES student,
    logitem_id INT NOT NULL CONSTRAINT uk_sbfow79puo0pd56584c8kmgfj UNIQUE
        CONSTRAINT fkd3ou6v8y4cvxwsi67cceixbmg REFERENCES logitem
);

INSERT INTO student(firstname, lastname) VALUES
    ('Ольга','Макеева'),
    ('Ольга','Соловьева'),
    ('Полина','Стефанская'),
    ('Евгений','Ильин'),
    ('Алексей','Кузнецов'),
    ('Даниль','Адигамов'),
    ('Юлия','Суслова'),
    ('Максим','Ростиславский'),
    ('Эдуард','Гайниев'),
    ('Юрий','Иванов'),
    ('Иван','Моря'),
    ('Роман','Головачев'),
    ('Игорь','Зубров'),
    ('Антон','Кадачигов'),
    ('Андрей','Булавин'),
    ('Максим','Маковеев'),
    ('Евгений','Юруть'),
    ('Арсений','Виноградов'),
    ('Александр','Варкан'),
    ('Олег','Гвоздь');
